// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WifiSD.Persistence.Repositories.DBContext;

namespace WifiSD.Persistence.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20220531160858_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WifiSD.Core.Entities.Movies.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Comedy"
                        });
                });

            modelBuilder.Entity("WifiSD.Core.Entities.Movies.MediumType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.HasKey("Code");

                    b.ToTable("MediumTypes");

                    b.HasData(
                        new
                        {
                            Code = "DVD",
                            Name = "Digital Versitale Disc"
                        },
                        new
                        {
                            Code = "BR",
                            Name = "Blue Ray"
                        },
                        new
                        {
                            Code = "BR-3D",
                            Name = "Blue Ray 3D"
                        },
                        new
                        {
                            Code = "BR-HDR",
                            Name = "Blue Ray High Definition Res."
                        },
                        new
                        {
                            Code = "VHS",
                            Name = "VHS"
                        });
                });

            modelBuilder.Entity("WifiSD.Core.Entities.Movies.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("MediumTypeCode")
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256)
                        .HasDefaultValue("Unknown");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("MediumTypeCode");

                    b.HasIndex("Name")
                        .HasName("IX_Movies_Name");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f3924ae-4753-4337-9a6b-fb597b5d85c7"),
                            GenreId = 4,
                            MediumTypeCode = "BR",
                            Name = "Schlimmer gehts immer",
                            Price = 20.99m,
                            Rating = (byte)5,
                            ReleaseDate = new DateTime(2017, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1bd83417-f42a-411d-a2fb-d35c85f5b8dc"),
                            GenreId = 1,
                            MediumTypeCode = "DVD",
                            Name = "Stirb langsam",
                            Price = 7.90m,
                            Rating = (byte)1,
                            ReleaseDate = new DateTime(1988, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0ee99d8e-26ff-40c4-80ef-3b30ab60ee29"),
                            GenreId = 3,
                            MediumTypeCode = "BR-3D",
                            Name = "Titanic",
                            Price = 9.90m,
                            Rating = (byte)3,
                            ReleaseDate = new DateTime(1994, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WifiSD.Core.Entities.Movies.Movie", b =>
                {
                    b.HasOne("WifiSD.Core.Entities.Movies.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WifiSD.Core.Entities.Movies.MediumType", "MediumType")
                        .WithMany("Movies")
                        .HasForeignKey("MediumTypeCode")
                        .HasConstraintName("FK_Movies_MediumTypes_MediumTypeCode")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
